FROM node:18.16

ENV TIME_ZONE=Europe/Paris

RUN echo $TIME_ZONE | tee /etc/timezone \
  && dpkg-reconfigure -f noninteractive tzdata

WORKDIR /usr/app

COPY ./api ./
RUN chown -R node:node /usr/app
USER node

# Install global dependencies
RUN yarn && yarn global add nodemon
