name: Node CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
        - name: mise_en_ligne
          run: echo "Je suis en production !"
    